spring:
  application:
    name: team1
  datasource:
    url: jdbc:mysql://localhost:3306/boopower
    username: root
    password: ohw62459930!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

springdoc:
  swagger-ui:
    path: swagger
    try-it-out-enabled: true
    filter: true
    operations-sorter: method
    display-request-duration: true
    use-root-path: true
  override-with-generic-response: false